### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by pirostudio** [takashi-matsuyama/my-favorites#3]
Hello,

Is it possible add to favorite posts list contact form and send email with posts list to admin?

**Comment by takashi-matsuyama** [comment]
Hello @pirostudio ,
Thank you for your question.
 
However, unfortunately, I have not tried this, but similar issues were discussed on the [WordPress forums](https://wordpress.org/support/topic/include-favorite-list-in-contact-form-7/).
I hope this is helpful to you.

https://wordpress.org/support/topic/include-favorite-list-in-contact-form-7/
https://wordpress.org/support/topic/simple-output-function-for-a-selectmenu/
https://wordpress.org/support/topic/send-favorited-items-to-email/

Thanks

**Comment by takashi-matsuyama** [comment]
Hello @pirostudio ,
Thank you for your question.

However, unfortunately, I have not tried this, but similar issues were discussed on the [WordPress forums](https://wordpress.org/support/topic/include-favorite-list-in-contact-form-7/).
I hope this is helpful to you.

https://wordpress.org/support/topic/include-favorite-list-in-contact-form-7/
https://wordpress.org/support/topic/simple-output-function-for-a-selectmenu/
https://wordpress.org/support/topic/send-favorited-items-to-email/

Thanks
